#!/usr/bin/env python3
"""
Ampler Launcher - write the website/skins/ folder listing into
website/skins/list.js.

A browser cannot list a folder, so the Skins page has two sources for its
skins: website/js/skins.js (the hand-kept list and its order) and this file,
which is generated from the folders actually on disk:

    python3 website/tools/bake-skins.py

Run it once after adding or removing a folder in website/skins/ and reload
index.html - nothing else to do. Deleting website/skins/list.js is always
safe: the page falls back to website/js/skins.js.

No server and no connection involved; the standard library is all it needs.
"""

import argparse
import json
import os
import sys


def find_root():
    # The repo root is the directory that holds index.html + README.md
    # (everything else lives under website/, so walk up from this file).
    d = os.path.dirname(os.path.abspath(__file__))
    while d != os.path.dirname(d):
        if (os.path.exists(os.path.join(d, "index.html"))
                and os.path.exists(os.path.join(d, "README.md"))):
            return d
        d = os.path.dirname(d)
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


ROOT = find_root()
SKINS_DIR = os.path.join(ROOT, "website", "skins")
SKINS_LIST_FILE = os.path.join(SKINS_DIR, "list.js")
SKIN_IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".webp", ".gif")


def skin_folders():
    """Every folder in website/skins/ that holds at least one image."""
    names = []
    try:
        for name in sorted(os.listdir(SKINS_DIR)):
            if name.startswith("."):
                continue
            folder = os.path.join(SKINS_DIR, name)
            if not os.path.isdir(folder):
                continue
            try:
                files = os.listdir(folder)
            except OSError:
                continue
            if any(f.lower().endswith(SKIN_IMAGE_EXTS) for f in files):
                names.append(name)
    except OSError:
        pass
    return names


def skins_list_js():
    """window.AMPLER_SKINS_FROM_DIR = [folders that look like skins]."""
    return ("/* generated by website/tools/bake-skins.py from the folders in\n"
            "   website/skins/ - edit the folders, not this file. */\n"
            "window.AMPLER_SKINS_FROM_DIR = %s;\n"
            % json.dumps(skin_folders(), ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(
        description="Write the website/skins/ folder listing into website/skins/list.js.")
    parser.add_argument("--dry-run", action="store_true",
                        help="print the listing instead of writing it (used by the checks)")
    args = parser.parse_args()

    folders = skin_folders()
    text = skins_list_js()

    if args.dry_run:
        # Exactly what would be written, so the checks can compare it with
        # what is actually on disk.
        sys.stdout.write(text)
        return 0

    with open(SKINS_LIST_FILE, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)

    print("Ampler Launcher - baked the skins listing")
    print("  folder : %s" % os.path.relpath(SKINS_LIST_FILE, ROOT))
    print("  skins  : %d" % len(folders))
    for name in folders:
        print("           %s" % name)
    print("\nReload index.html to see them. Nothing else to do.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
